### ISSUE TITLE
error calling match() on min_conf

### ISSUE THREAD

**Issue by hqhoang** [baudneo/neo-pyzm#2]
in detect_sequence.py, near line 483:
```
if min_conf:
    # Allow for 0.XX , 34 or 34% input for confidence - 34 would be evaluated as 34%
    _m = re.match(r"(\d*\.?\d*)(%)?$", min_conf, re.IGNORECASE)
```
TypeError: expected string or bytes-like object

We might want to wrap `str(min_conf)`?

**Comment by baudneo** [comment]
Yes, exactly. I had caught the error yesterday but forgot to push the fix. https://github.com/baudneo/neo-pyzm/commit/8ab461ef4041c04f90810af91fbe8606d5fd9272 should fix this issue.

Thank you for opening an issue!

**Comment by baudneo** [comment]
Closing as the commit seems to have cleared this issue up.
